"""
Generates one podcast episode, entirely within this job.

What this does, step by step:
1. Calls the Anthropic API directly (with web search) to write today's briefing.
2. Sends that text to Google Cloud Text-to-Speech and saves the result as an MP3.
3. Adds the new episode to docs/episodes.json (a running log of every episode).
4. Rebuilds docs/feed.xml from that log -- this is the file podcast apps actually read.

This version writes the briefing itself rather than reading it from a Google Doc,
so there's no dependency on Claude's scheduled task or your computer being on --
everything happens inside this one GitHub Actions job, on GitHub's own servers.

The one-time setup this script depends on (Google Cloud project, service account,
Anthropic API key, GitHub secrets) is documented in SETUP.md.
"""

from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

import anthropic
from google.api_core import exceptions as google_exceptions
from google.oauth2 import service_account
from google.cloud import texttospeech
from mutagen.mp3 import MP3

# ---- Things you'll likely want to change ----
SHOW_TITLE = "James's Morning Briefing"
SHOW_DESCRIPTION = "A personal daily news briefing, generated by Claude."
SHOW_AUTHOR = "James"
SHOW_LANGUAGE = "en-us"
# Any voice from Google Cloud's free WaveNet tier works here -- browse more at
# https://cloud.google.com/text-to-speech/docs/voices
VOICE_NAME = "en-US-Studio-O"
SITE_URL = "https://jamesroberthuber.github.io/news-podcast"
MAX_EPISODES_IN_FEED = 30  # older episodes stay on disk but drop out of the feed
# Google caps each TTS request at 5000 bytes, measured on the rendered SSML payload -- which
# includes the <speak>/<break> tags and &amp;-style entity escapes, so it's larger than the raw
# text. Budget chunks against the actual SSML size, with headroom below the hard limit.
SSML_HARD_LIMIT_BYTES = 5000
MAX_SSML_BYTES = 4800
CLAUDE_MODEL = "claude-haiku-4-5"  # cheaper than Sonnet 5; no output_config.effort knob -- Haiku doesn't support it
MAX_WEB_SEARCHES = 8  # lower search cap -> less chance of hitting the server-side pause_turn wall
PROMPT_PATH = Path(__file__).parent / "briefing_prompt.txt"

# Guardrails. A real ~5-minute briefing is several thousand characters and a couple of minutes
# of audio; anything well below these floors means generation or synthesis went wrong. The
# workflow only commits when this script exits zero, so raising on a bad result means a broken
# episode surfaces as a red Actions run instead of a silently published 4-second clip.
MIN_BRIEFING_CHARS = 1500
MIN_DURATION_SECONDS = 90
MIN_AUDIO_BYTES = 20_000
MAX_TOKENS = 16000

# The server-side web-search loop can pause mid-generation (stop_reason "pause_turn"); resume
# the same turn up to this many times before giving up rather than shipping a partial briefing.
# Kept low because every resend re-bills the whole accumulated conversation -- a run that needs
# many continuations is exactly the runaway-cost case, so failing fast here is cheaper than
# letting it grind through six rounds. A skipped episode is fine; a $2+ episode isn't.
MAX_PAUSE_CONTINUATIONS = 3
API_RETRY_ATTEMPTS = 4  # transient-error retries for both the Anthropic and Google TTS calls

DOCS_DIR = Path("docs")
EPISODES_DIR = DOCS_DIR / "episodes"
EPISODES_LOG = DOCS_DIR / "episodes.json"
FEED_PATH = DOCS_DIR / "feed.xml"


def _assistant_text(content) -> list[str]:
    """Pulls the text fragments out of one assistant turn's content blocks.

    Web search runs server-side mid-response, so a single turn's `content` interleaves
    text blocks with server_tool_use / web_search_tool_result blocks. The text blocks are
    fragments of one continuous stream (a search can split even a single sentence), so the
    caller joins them with no separator. We keep only `text` blocks and drop the tool blocks.
    """
    return [block.text for block in content if block.type == "text"]


def generate_briefing_text() -> str:
    """Asks Claude to research and write today's briefing, using web search.

    The web search tool runs on Anthropic's servers, so Claude searches several times within
    the turn before writing the script. If that server-side loop hits its iteration cap the
    turn stops with stop_reason "pause_turn" and must be resumed -- otherwise the briefing is
    silently truncated. We resume until the turn ends normally, accumulating text across every
    turn, and treat any non-`end_turn` stop reason (max_tokens, refusal, ...) as a hard failure
    so a partial briefing fails the job rather than being published.
    """
    client = anthropic.Anthropic(
        api_key=os.environ["ANTHROPIC_API_KEY"],
        max_retries=API_RETRY_ATTEMPTS,  # SDK retries 429/5xx/connection errors with backoff
    )
    # cache_control on the system prompt means every pause_turn resend (below) re-reads this
    # instead of re-billing it at full price -- it's identical on every request in the loop.
    system = [{
        "type": "text",
        "text": PROMPT_PATH.read_text(),
        "cache_control": {"type": "ephemeral"},
    }]
    # web_search_20260209 (dynamic filtering) isn't available on Haiku 4.5 -- this is the
    # basic variant older/smaller models use.
    tools = [{"type": "web_search_20250305", "name": "web_search", "max_uses": MAX_WEB_SEARCHES}]
    messages = [{"role": "user", "content": "Go"}]

    text_fragments: list[str] = []
    for attempt in range(MAX_PAUSE_CONTINUATIONS):
        response = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=MAX_TOKENS,
            system=system,
            tools=tools,
            messages=messages,
        )
        text_fragments += _assistant_text(response.content)

        if response.stop_reason == "pause_turn":
            # Server-side tool loop paused mid-generation. Feed the partial turn back so the
            # next request resumes exactly where it left off (do NOT add a "continue" message).
            # Cache-mark the last block too, so a second pause only pays full price for what's
            # new since this point rather than re-billing everything gathered so far.
            content = response.model_dump()["content"]
            if content:
                content[-1]["cache_control"] = {"type": "ephemeral"}
            messages.append({"role": "assistant", "content": content})
            print(f"Turn paused (attempt {attempt + 1}); resuming to finish the briefing.")
            continue

        if response.stop_reason != "end_turn":
            raise SystemExit(
                f"Briefing generation stopped with stop_reason {response.stop_reason!r} "
                f"-- refusing to publish a partial or refused briefing."
            )
        break
    else:
        raise SystemExit(
            f"Briefing still pausing after {MAX_PAUSE_CONTINUATIONS} continuations -- aborting."
        )

    text = "".join(text_fragments).strip()
    print(f"Generated {len(text)} characters across {len(text_fragments)} text block(s).")
    return text


def _sanitize_for_speech(text: str) -> str:
    """Strips markdown/decorative characters that Google TTS reads aloud literally.

    Claude sometimes separates sections with a horizontal-rule-style line (---, ***, ...),
    a bullet marker, or markdown emphasis (**bold**) even when told to write plain prose.
    Google's Studio voices don't silently skip these -- a lone separator character between
    sections gets vocalized (e.g. as "dot"), which is audible and jarring in a podcast.
    """
    lines = []
    for line in text.split("\n"):
        stripped = line.strip()
        # Drop separator-only lines: ---, ***, ..., •••, em/en-dash rules, or any mix.
        if stripped and re.fullmatch(r"[-–—*_.•●▪‣~=]+", stripped):
            continue
        # Strip a leading list-bullet marker but keep the rest of the line's content.
        stripped = re.sub(r"^[-*•●▪‣]\s+", "", stripped)
        # Remove markdown emphasis markers -- they're never meant to be read aloud.
        stripped = re.sub(r"(\*\*|__|\*|_)", "", stripped)
        lines.append(stripped)

    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)  # collapse blank runs left by removed separators
    return text.strip()


def _split_into_chunks(text: str, max_ssml_bytes: int = MAX_SSML_BYTES) -> list[str]:
    """Splits text into pieces that stay under Google's per-request TTS byte limit.

    The limit is measured on the rendered SSML, not the raw text, so each candidate is sized
    via `_to_ssml` (which adds the <speak>/<break> tags and entity escapes). Breaks at
    paragraph boundaries first, falling back to sentence boundaries for any paragraph that's
    still too long on its own, so the audio doesn't get cut off mid-thought.
    """
    def fits(candidate: str) -> bool:
        return len(_to_ssml(candidate).encode("utf-8")) <= max_ssml_bytes

    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    chunks: list[str] = []
    current = ""

    def flush():
        nonlocal current
        if current:
            chunks.append(current.strip())
            current = ""

    for paragraph in paragraphs:
        candidate = f"{current}\n{paragraph}".strip() if current else paragraph
        if fits(candidate):
            current = candidate
            continue

        flush()
        sentences = re.split(r"(?<=[.!?])\s+", paragraph)
        for sentence in sentences:
            candidate = f"{current} {sentence}".strip() if current else sentence
            if fits(candidate):
                current = candidate
            else:
                flush()
                current = sentence  # a single sentence over the limit is rare; send as-is

    flush()
    return chunks


def _load_tts_credentials():
    creds_info = json.loads(os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"])
    return service_account.Credentials.from_service_account_info(creds_info)


SECTION_PAUSE_MS = 700  # silence inserted between paragraphs/sections so they don't blur together


def _to_ssml(chunk: str) -> str:
    """Wraps a chunk in SSML, inserting a deliberate pause between each paragraph.

    Plain-text synthesis relies on Claude's punctuation alone for pacing, which reads
    as one continuous stream with no sense of moving from one story to the next. Each
    paragraph in the briefing is one story/section (see _split_into_chunks), so a pause
    at every paragraph boundary gives the listener an audible break between sections.
    """
    paragraphs = [p for p in chunk.split("\n") if p.strip()]
    body = f'<break time="{SECTION_PAUSE_MS}ms"/>'.join(escape(p) for p in paragraphs)
    return f"<speak>{body}</speak>"


# Transient Google API errors worth retrying (rate limits, 5xx, timeouts). A 400
# (InvalidArgument -- e.g. an oversized SSML chunk) is a real bug, so it's deliberately not
# listed here: it propagates and fails the job loudly rather than being retried pointlessly.
_RETRYABLE_TTS_ERRORS = (
    google_exceptions.ResourceExhausted,
    google_exceptions.ServiceUnavailable,
    google_exceptions.DeadlineExceeded,
    google_exceptions.InternalServerError,
    google_exceptions.GatewayTimeout,
)


def _synthesize_chunk(client, synthesis_input, voice, audio_config):
    """One TTS request, retried on transient errors with exponential backoff."""
    for attempt in range(API_RETRY_ATTEMPTS):
        try:
            return client.synthesize_speech(
                input=synthesis_input, voice=voice, audio_config=audio_config
            )
        except _RETRYABLE_TTS_ERRORS as exc:
            if attempt == API_RETRY_ATTEMPTS - 1:
                raise
            wait = 2 ** attempt
            print(f"    TTS request failed ({exc.__class__.__name__}); retrying in {wait}s")
            time.sleep(wait)


def synthesize_audio(text: str, out_path: Path) -> None:
    """Converts text to an MP3 using a Google Cloud voice, with pauses between sections.

    Google caps each request at 5000 bytes, so longer briefings get split
    into pieces, synthesized separately, and the resulting audio is joined
    into one file. Simple concatenation like this can leave a very faint
    seam between pieces -- usually inaudible for spoken word, but if it's
    ever noticeable, joining with ffmpeg instead would smooth it out.

    Raises SystemExit if any chunk would exceed Google's SSML limit, a chunk comes back
    with no audio, or the joined result is implausibly small -- so a broken synthesis fails
    the job instead of publishing a silent or truncated episode.
    """
    creds = _load_tts_credentials()
    client = texttospeech.TextToSpeechClient(credentials=creds)
    voice = texttospeech.VoiceSelectionParams(language_code="en-US", name=VOICE_NAME)
    audio_config = texttospeech.AudioConfig(audio_encoding=texttospeech.AudioEncoding.MP3)

    chunks = _split_into_chunks(text)
    print(f"Synthesizing {len(chunks)} chunk(s)...")

    audio_bytes = b""
    for i, chunk in enumerate(chunks, 1):
        ssml = _to_ssml(chunk)
        ssml_bytes = len(ssml.encode("utf-8"))
        if ssml_bytes > SSML_HARD_LIMIT_BYTES:
            raise SystemExit(
                f"SSML chunk {i} is {ssml_bytes} bytes, over Google's {SSML_HARD_LIMIT_BYTES}-byte "
                f"limit -- tighten chunking (a single over-long sentence can cause this)."
            )
        synthesis_input = texttospeech.SynthesisInput(ssml=ssml)
        response = _synthesize_chunk(client, synthesis_input, voice, audio_config)
        if not response.audio_content:
            raise SystemExit(f"TTS returned empty audio for chunk {i} -- refusing to publish.")
        audio_bytes += response.audio_content
        print(f"  chunk {i}/{len(chunks)}: {len(chunk)} chars, {ssml_bytes} SSML bytes")

    if len(audio_bytes) < MIN_AUDIO_BYTES:
        raise SystemExit(
            f"Synthesized audio is only {len(audio_bytes)} bytes (min {MIN_AUDIO_BYTES}) "
            f"-- something went wrong; refusing to publish."
        )

    out_path.write_bytes(audio_bytes)


def get_duration_seconds(audio_path: Path) -> int | None:
    """Reads the real length off the MP3 so the feed can report it accurately.

    Without this, podcast apps have to guess the duration themselves, and
    some (Apple Podcasts included) show 0:00 and mark the episode as
    instantly finished rather than actually playing it.
    """
    try:
        return round(MP3(str(audio_path)).info.length)
    except Exception as exc:  # don't let a metadata hiccup break the whole run
        print(f"Could not read duration: {exc}")
        return None


def upsert_episode(episodes: list, new_episode: dict) -> list:
    """Adds an episode, replacing any existing entry for the same file.

    The workflow can run more than once on the same day -- a manual test,
    a retry after a failure -- and since the filename is date-based, a
    second run would otherwise add a second entry with the same guid as
    the first. Duplicate guids in a feed confuse podcast apps rather than
    just producing an extra episode, so this keeps exactly one entry per
    filename, always reflecting the most recent run.
    """
    episodes = [ep for ep in episodes if ep["filename"] != new_episode["filename"]]
    episodes.append(new_episode)
    return episodes


def load_episode_log() -> list:
    if EPISODES_LOG.exists():
        return json.loads(EPISODES_LOG.read_text())
    return []


def save_episode_log(episodes: list) -> None:
    EPISODES_LOG.write_text(json.dumps(episodes, indent=2))


def build_feed_xml(episodes: list) -> str:
    """Rebuilds the whole RSS feed from the episode log, newest episode first."""
    items = []
    for ep in reversed(episodes[-MAX_EPISODES_IN_FEED:]):
        filename = ep.get("filename")
        file_size = ep.get("file_size")
        if not filename or not file_size:
            # A malformed/legacy log entry shouldn't abort the whole feed rebuild after the
            # new audio is already on disk -- skip it rather than raising KeyError.
            print(f"Skipping malformed episode-log entry: {ep!r}")
            continue
        title = ep.get("title", filename)
        audio_url = f"{SITE_URL}/episodes/{filename}"
        duration = ep.get("duration_seconds")
        duration_tag = f"\n      <itunes:duration>{duration}</itunes:duration>" if duration else ""
        items.append(f"""
    <item>
      <title>{escape(title)}</title>
      <pubDate>{ep.get('pub_date', '')}</pubDate>
      <guid isPermaLink="false">{filename}</guid>
      <enclosure url="{audio_url}" type="audio/mpeg" length="{file_size}" />{duration_tag}
      <description>{escape(title)}</description>
    </item>""")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>{escape(SHOW_TITLE)}</title>
    <description>{escape(SHOW_DESCRIPTION)}</description>
    <link>{SITE_URL}</link>
    <language>{SHOW_LANGUAGE}</language>
    <itunes:author>{escape(SHOW_AUTHOR)}</itunes:author>
    <itunes:explicit>false</itunes:explicit>
    <itunes:category text="News" />
    <itunes:image href="{SITE_URL}/artwork.jpg" />
    {''.join(items)}
  </channel>
</rss>
"""


def main() -> None:
    EPISODES_DIR.mkdir(parents=True, exist_ok=True)

    text = _sanitize_for_speech(generate_briefing_text())
    if len(text) < MIN_BRIEFING_CHARS:
        raise SystemExit(
            f"Briefing is only {len(text)} chars (min {MIN_BRIEFING_CHARS}) -- refusing to "
            f"publish. Likely a failed search, an empty response, or a refusal."
        )

    today = datetime.now(timezone.utc)
    filename = f"{today:%Y-%m-%d}.mp3"
    audio_path = EPISODES_DIR / filename

    # Saved alongside the audio so the generated script can be inspected directly,
    # instead of only being able to listen to the synthesized result.
    text_path = EPISODES_DIR / f"{today:%Y-%m-%d}.txt"
    text_path.write_text(text)

    synthesize_audio(text, audio_path)

    duration_seconds = get_duration_seconds(audio_path)
    if duration_seconds is None or duration_seconds < MIN_DURATION_SECONDS:
        raise SystemExit(
            f"Episode duration {duration_seconds}s is below the {MIN_DURATION_SECONDS}s floor "
            f"-- refusing to publish a truncated or empty episode."
        )

    episodes = load_episode_log()
    episodes = upsert_episode(episodes, {
        "title": f"Briefing -- {today:%B %-d, %Y}",
        "pub_date": today.strftime("%a, %d %b %Y %H:%M:%S +0000"),
        "filename": filename,
        "file_size": audio_path.stat().st_size,
        "duration_seconds": duration_seconds,
    })
    save_episode_log(episodes)

    FEED_PATH.write_text(build_feed_xml(episodes))
    print(f"Published episode: {filename}")


if __name__ == "__main__":
    main()
