"""
Generates one podcast episode from the day's briefing text.

What this does, step by step:
1. Reads the briefing text out of a specific Google Doc (using a service account).
2. Sends that text to Google Cloud Text-to-Speech and saves the result as an MP3.
3. Adds the new episode to docs/episodes.json (a running log of every episode).
4. Rebuilds docs/feed.xml from that log -- this is the file podcast apps actually read.

The one-time setup this script depends on (Google Cloud project, service account,
GitHub secrets, etc.) is documented in SETUP.md.
"""

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

from google.oauth2 import service_account
from googleapiclient.discovery import build
from google.cloud import texttospeech
from mutagen.mp3 import MP3

# ---- Things you'll likely want to change ----
SHOW_TITLE = "James's Morning Briefing"
SHOW_DESCRIPTION = "A personal daily news briefing, generated by Claude."
SHOW_AUTHOR = "James"
SHOW_LANGUAGE = "en-us"
# Any voice from Google Cloud's free WaveNet tier works here -- browse more at
# https://cloud.google.com/text-to-speech/docs/voices
VOICE_NAME = "en-US-Wavenet-D"
# Fill this in once GitHub Pages is live (Settings -> Pages in your repo).
SITE_URL = "https://jamesroberthuber.github.io/news-podcast"
MAX_EPISODES_IN_FEED = 30  # older episodes stay on disk but drop out of the feed
MAX_CHUNK_BYTES = 4800  # Google's per-request TTS limit is 5000 bytes; stay a bit under it

DOCS_DIR = Path("docs")
EPISODES_DIR = DOCS_DIR / "episodes"
EPISODES_LOG = DOCS_DIR / "episodes.json"
FEED_PATH = DOCS_DIR / "feed.xml"


def _load_credentials(scopes=None):
    creds_info = json.loads(os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"])
    if scopes:
        return service_account.Credentials.from_service_account_info(creds_info, scopes=scopes)
    return service_account.Credentials.from_service_account_info(creds_info)


def fetch_briefing_text() -> str:
    """Finds the most recently created Doc in the shared folder and reads it.

    Claude's Drive connector can create new files but can't edit an existing
    one in place, so each run creates a fresh Doc rather than overwriting one.
    This looks up whichever Doc in that folder is newest.
    """
    creds = _load_credentials(scopes=["https://www.googleapis.com/auth/drive.readonly"])
    drive = build("drive", "v3", credentials=creds)
    folder_id = os.environ["GOOGLE_DRIVE_FOLDER_ID"]

    results = drive.files().list(
        q=(
            f"'{folder_id}' in parents "
            "and mimeType='application/vnd.google-apps.document' "
            "and trashed=false"
        ),
        orderBy="createdTime desc",
        pageSize=1,
        fields="files(id, name, createdTime)",
    ).execute()

    files = results.get("files", [])
    if not files:
        print("No briefing doc found in the folder today -- skipping.")
        return ""

    doc_id = files[0]["id"]
    exported = drive.files().export(fileId=doc_id, mimeType="text/plain").execute()
    return exported.decode("utf-8").strip()


def _split_into_chunks(text: str, max_bytes: int = MAX_CHUNK_BYTES) -> list[str]:
    """Splits text into pieces under Google's per-request TTS byte limit.

    Breaks at paragraph boundaries first, falling back to sentence
    boundaries for any paragraph that's still too long on its own, so
    the audio doesn't get cut off mid-thought.
    """
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    chunks: list[str] = []
    current = ""

    def flush():
        nonlocal current
        if current:
            chunks.append(current.strip())
            current = ""

    for paragraph in paragraphs:
        candidate = f"{current}\n{paragraph}".strip() if current else paragraph
        if len(candidate.encode("utf-8")) <= max_bytes:
            current = candidate
            continue

        flush()
        sentences = re.split(r"(?<=[.!?])\s+", paragraph)
        for sentence in sentences:
            candidate = f"{current} {sentence}".strip() if current else sentence
            if len(candidate.encode("utf-8")) <= max_bytes:
                current = candidate
            else:
                flush()
                current = sentence  # a single sentence over the limit is rare; send as-is

    flush()
    return chunks


def synthesize_audio(text: str, out_path: Path) -> None:
    """Converts text to an MP3 using a free-tier Google Cloud WaveNet voice.

    Google caps each request at 5000 bytes, so longer briefings get split
    into pieces, synthesized separately, and the resulting audio is joined
    into one file. Simple concatenation like this can leave a very faint
    seam between pieces -- usually inaudible for spoken word, but if it's
    ever noticeable, joining with ffmpeg instead would smooth it out.
    """
    creds = _load_credentials()
    client = texttospeech.TextToSpeechClient(credentials=creds)
    voice = texttospeech.VoiceSelectionParams(language_code="en-US", name=VOICE_NAME)
    audio_config = texttospeech.AudioConfig(audio_encoding=texttospeech.AudioEncoding.MP3)

    chunks = _split_into_chunks(text)
    print(f"Synthesizing {len(chunks)} chunk(s)...")

    audio_bytes = b""
    for i, chunk in enumerate(chunks, 1):
        synthesis_input = texttospeech.SynthesisInput(text=chunk)
        response = client.synthesize_speech(input=synthesis_input, voice=voice, audio_config=audio_config)
        audio_bytes += response.audio_content
        print(f"  chunk {i}/{len(chunks)}: {len(chunk)} characters")

    out_path.write_bytes(audio_bytes)


def get_duration_seconds(audio_path: Path) -> int | None:
    """Reads the real length off the MP3 so the feed can report it accurately.

    Without this, podcast apps have to guess the duration themselves, and
    some (Apple Podcasts included) show 0:00 and mark the episode as
    instantly finished rather than actually playing it.
    """
    try:
        return round(MP3(str(audio_path)).info.length)
    except Exception as exc:  # don't let a metadata hiccup break the whole run
        print(f"Could not read duration: {exc}")
        return None


def upsert_episode(episodes: list, new_episode: dict) -> list:
    """Adds an episode, replacing any existing entry for the same file.

    The workflow can run more than once on the same day -- a manual test,
    a retry after a failure -- and since the filename is date-based, a
    second run would otherwise add a second entry with the same guid as
    the first. Duplicate guids in a feed confuse podcast apps rather than
    just producing an extra episode, so this keeps exactly one entry per
    filename, always reflecting the most recent run.
    """
    episodes = [ep for ep in episodes if ep["filename"] != new_episode["filename"]]
    episodes.append(new_episode)
    return episodes


def load_episode_log() -> list:
    if EPISODES_LOG.exists():
        return json.loads(EPISODES_LOG.read_text())
    return []


def save_episode_log(episodes: list) -> None:
    EPISODES_LOG.write_text(json.dumps(episodes, indent=2))


def build_feed_xml(episodes: list) -> str:
    """Rebuilds the whole RSS feed from the episode log, newest episode first."""
    items = []
    for ep in reversed(episodes[-MAX_EPISODES_IN_FEED:]):
        audio_url = f"{SITE_URL}/episodes/{ep['filename']}"
        duration = ep.get("duration_seconds")
        duration_tag = f"\n      <itunes:duration>{duration}</itunes:duration>" if duration else ""
        items.append(f"""
    <item>
      <title>{escape(ep['title'])}</title>
      <pubDate>{ep['pub_date']}</pubDate>
      <guid isPermaLink="false">{ep['filename']}</guid>
      <enclosure url="{audio_url}" type="audio/mpeg" length="{ep['file_size']}" />{duration_tag}
      <description>{escape(ep['title'])}</description>
    </item>""")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>{escape(SHOW_TITLE)}</title>
    <description>{escape(SHOW_DESCRIPTION)}</description>
    <link>{SITE_URL}</link>
    <language>{SHOW_LANGUAGE}</language>
    <itunes:author>{escape(SHOW_AUTHOR)}</itunes:author>
    <itunes:explicit>false</itunes:explicit>
    <itunes:category text="News" />
    <itunes:image href="{SITE_URL}/artwork.jpg" />
    {''.join(items)}
  </channel>
</rss>
"""


def main() -> None:
    EPISODES_DIR.mkdir(parents=True, exist_ok=True)

    text = fetch_briefing_text()
    if not text:
        print("No briefing text found today -- skipping.")
        return

    today = datetime.now(timezone.utc)
    filename = f"{today:%Y-%m-%d}.mp3"
    audio_path = EPISODES_DIR / filename
    synthesize_audio(text, audio_path)
    duration_seconds = get_duration_seconds(audio_path)

    episodes = load_episode_log()
    episodes = upsert_episode(episodes, {
        "title": f"Briefing -- {today:%B %-d, %Y}",
        "pub_date": today.strftime("%a, %d %b %Y %H:%M:%S +0000"),
        "filename": filename,
        "file_size": audio_path.stat().st_size,
        "duration_seconds": duration_seconds,
    })
    save_episode_log(episodes)

    FEED_PATH.write_text(build_feed_xml(episodes))
    print(f"Published episode: {filename}")


if __name__ == "__main__":
    main()
