"""
Generates one podcast episode, entirely within this job.

What this does, step by step:
1. Calls the Anthropic API directly (with web search) to write today's briefing.
2. Sends that text to Google Cloud Text-to-Speech and saves the result as an MP3.
3. Adds the new episode to docs/episodes.json (a running log of every episode).
4. Rebuilds docs/feed.xml from that log -- this is the file podcast apps actually read.

This version writes the briefing itself rather than reading it from a Google Doc,
so there's no dependency on Claude's scheduled task or your computer being on --
everything happens inside this one GitHub Actions job, on GitHub's own servers.

The one-time setup this script depends on (Google Cloud project, service account,
Anthropic API key, GitHub secrets) is documented in SETUP.md.
"""

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

import anthropic
from google.oauth2 import service_account
from google.cloud import texttospeech
from mutagen.mp3 import MP3

# ---- Things you'll likely want to change ----
SHOW_TITLE = "James's Morning Briefing"
SHOW_DESCRIPTION = "A personal daily news briefing, generated by Claude."
SHOW_AUTHOR = "James"
SHOW_LANGUAGE = "en-us"
# Any voice from Google Cloud's free WaveNet tier works here -- browse more at
# https://cloud.google.com/text-to-speech/docs/voices
VOICE_NAME = "en-US-Studio-O"
SITE_URL = "https://jamesroberthuber.github.io/news-podcast"
MAX_EPISODES_IN_FEED = 30  # older episodes stay on disk but drop out of the feed
MAX_CHUNK_BYTES = 4300  # Google's per-request TTS limit is 5000 bytes; leaves room for the
                        # <speak>/<break> SSML tags added around each chunk before sending
CLAUDE_MODEL = "claude-sonnet-5"  # try "claude-haiku-4-5-20251001" for a week and compare quality
PROMPT_PATH = Path(__file__).parent / "briefing_prompt.txt"

DOCS_DIR = Path("docs")
EPISODES_DIR = DOCS_DIR / "episodes"
EPISODES_LOG = DOCS_DIR / "episodes.json"
FEED_PATH = DOCS_DIR / "feed.xml"


def generate_briefing_text() -> str:
    """Asks Claude to research and write today's briefing, using web search.

    This is a single API call -- the web search tool runs on Anthropic's
    servers, so Claude can search multiple times within this one request
    before returning the finished script.
    """
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    system_prompt = PROMPT_PATH.read_text()

    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=16000,
        system=system_prompt,
        tools=[{"type": "web_search_20260209", "name": "web_search", "max_uses": 15}],
        messages=[{"role": "user", "content": "Go"}],
    )

    if response.stop_reason == "max_tokens":
        print("WARNING: response hit the max_tokens limit -- the briefing may be truncated.")

    # Claude's response can include text blocks written between web searches (e.g. "let me
    # check one more source") alongside the actual finished script. Only the last text block
    # is the complete briefing -- earlier ones are dropped so stray narration never reaches
    # the audio, even if Claude ignores the "no narration" instruction in the prompt.
    text_blocks = [block.text for block in response.content if block.type == "text"]
    if len(text_blocks) > 1:
        print(f"WARNING: got {len(text_blocks)} text blocks -- dropping all but the last one. Dropped blocks:")
        for block in text_blocks[:-1]:
            print(f"  DROPPED: {block[:200]!r}")

    text = text_blocks[-1].strip() if text_blocks else ""
    print(f"Generated {len(text)} characters (stop_reason: {response.stop_reason})")
    return text


def _sanitize_for_speech(text: str) -> str:
    """Strips markdown/decorative characters that Google TTS reads aloud literally.

    Claude sometimes separates sections with a horizontal-rule-style line (---, ***, ...),
    a bullet marker, or markdown emphasis (**bold**) even when told to write plain prose.
    Google's Studio voices don't silently skip these -- a lone separator character between
    sections gets vocalized (e.g. as "dot"), which is audible and jarring in a podcast.
    """
    lines = []
    for line in text.split("\n"):
        stripped = line.strip()
        # Drop separator-only lines: ---, ***, ..., •••, or any mix of those characters.
        if stripped and re.fullmatch(r"[-*_.•●▪‣~=]+", stripped):
            continue
        # Strip a leading list-bullet marker but keep the rest of the line's content.
        stripped = re.sub(r"^[-*•●▪‣]\s+", "", stripped)
        # Remove markdown emphasis markers -- they're never meant to be read aloud.
        stripped = re.sub(r"(\*\*|__|\*|_)", "", stripped)
        lines.append(stripped)

    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)  # collapse blank runs left by removed separators
    return text.strip()


def _split_into_chunks(text: str, max_bytes: int = MAX_CHUNK_BYTES) -> list[str]:
    """Splits text into pieces under Google's per-request TTS byte limit.

    Breaks at paragraph boundaries first, falling back to sentence
    boundaries for any paragraph that's still too long on its own, so
    the audio doesn't get cut off mid-thought.
    """
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    chunks: list[str] = []
    current = ""

    def flush():
        nonlocal current
        if current:
            chunks.append(current.strip())
            current = ""

    for paragraph in paragraphs:
        candidate = f"{current}\n{paragraph}".strip() if current else paragraph
        if len(candidate.encode("utf-8")) <= max_bytes:
            current = candidate
            continue

        flush()
        sentences = re.split(r"(?<=[.!?])\s+", paragraph)
        for sentence in sentences:
            candidate = f"{current} {sentence}".strip() if current else sentence
            if len(candidate.encode("utf-8")) <= max_bytes:
                current = candidate
            else:
                flush()
                current = sentence  # a single sentence over the limit is rare; send as-is

    flush()
    return chunks


def _load_tts_credentials():
    creds_info = json.loads(os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"])
    return service_account.Credentials.from_service_account_info(creds_info)


SECTION_PAUSE_MS = 700  # silence inserted between paragraphs/sections so they don't blur together


def _to_ssml(chunk: str) -> str:
    """Wraps a chunk in SSML, inserting a deliberate pause between each paragraph.

    Plain-text synthesis relies on Claude's punctuation alone for pacing, which reads
    as one continuous stream with no sense of moving from one story to the next. Each
    paragraph in the briefing is one story/section (see _split_into_chunks), so a pause
    at every paragraph boundary gives the listener an audible break between sections.
    """
    paragraphs = [p for p in chunk.split("\n") if p.strip()]
    body = f'<break time="{SECTION_PAUSE_MS}ms"/>'.join(escape(p) for p in paragraphs)
    return f"<speak>{body}</speak>"


def synthesize_audio(text: str, out_path: Path) -> None:
    """Converts text to an MP3 using a Google Cloud voice, with pauses between sections.

    Google caps each request at 5000 bytes, so longer briefings get split
    into pieces, synthesized separately, and the resulting audio is joined
    into one file. Simple concatenation like this can leave a very faint
    seam between pieces -- usually inaudible for spoken word, but if it's
    ever noticeable, joining with ffmpeg instead would smooth it out.
    """
    creds = _load_tts_credentials()
    client = texttospeech.TextToSpeechClient(credentials=creds)
    voice = texttospeech.VoiceSelectionParams(language_code="en-US", name=VOICE_NAME)
    audio_config = texttospeech.AudioConfig(audio_encoding=texttospeech.AudioEncoding.MP3)

    chunks = _split_into_chunks(text)
    print(f"Synthesizing {len(chunks)} chunk(s)...")

    audio_bytes = b""
    for i, chunk in enumerate(chunks, 1):
        synthesis_input = texttospeech.SynthesisInput(ssml=_to_ssml(chunk))
        response = client.synthesize_speech(input=synthesis_input, voice=voice, audio_config=audio_config)
        audio_bytes += response.audio_content
        print(f"  chunk {i}/{len(chunks)}: {len(chunk)} characters")

    out_path.write_bytes(audio_bytes)


def get_duration_seconds(audio_path: Path) -> int | None:
    """Reads the real length off the MP3 so the feed can report it accurately.

    Without this, podcast apps have to guess the duration themselves, and
    some (Apple Podcasts included) show 0:00 and mark the episode as
    instantly finished rather than actually playing it.
    """
    try:
        return round(MP3(str(audio_path)).info.length)
    except Exception as exc:  # don't let a metadata hiccup break the whole run
        print(f"Could not read duration: {exc}")
        return None


def upsert_episode(episodes: list, new_episode: dict) -> list:
    """Adds an episode, replacing any existing entry for the same file.

    The workflow can run more than once on the same day -- a manual test,
    a retry after a failure -- and since the filename is date-based, a
    second run would otherwise add a second entry with the same guid as
    the first. Duplicate guids in a feed confuse podcast apps rather than
    just producing an extra episode, so this keeps exactly one entry per
    filename, always reflecting the most recent run.
    """
    episodes = [ep for ep in episodes if ep["filename"] != new_episode["filename"]]
    episodes.append(new_episode)
    return episodes


def load_episode_log() -> list:
    if EPISODES_LOG.exists():
        return json.loads(EPISODES_LOG.read_text())
    return []


def save_episode_log(episodes: list) -> None:
    EPISODES_LOG.write_text(json.dumps(episodes, indent=2))


def build_feed_xml(episodes: list) -> str:
    """Rebuilds the whole RSS feed from the episode log, newest episode first."""
    items = []
    for ep in reversed(episodes[-MAX_EPISODES_IN_FEED:]):
        audio_url = f"{SITE_URL}/episodes/{ep['filename']}"
        duration = ep.get("duration_seconds")
        duration_tag = f"\n      <itunes:duration>{duration}</itunes:duration>" if duration else ""
        items.append(f"""
    <item>
      <title>{escape(ep['title'])}</title>
      <pubDate>{ep['pub_date']}</pubDate>
      <guid isPermaLink="false">{ep['filename']}</guid>
      <enclosure url="{audio_url}" type="audio/mpeg" length="{ep['file_size']}" />{duration_tag}
      <description>{escape(ep['title'])}</description>
    </item>""")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>{escape(SHOW_TITLE)}</title>
    <description>{escape(SHOW_DESCRIPTION)}</description>
    <link>{SITE_URL}</link>
    <language>{SHOW_LANGUAGE}</language>
    <itunes:author>{escape(SHOW_AUTHOR)}</itunes:author>
    <itunes:explicit>false</itunes:explicit>
    <itunes:category text="News" />
    <itunes:image href="{SITE_URL}/artwork.jpg" />
    {''.join(items)}
  </channel>
</rss>
"""


def main() -> None:
    EPISODES_DIR.mkdir(parents=True, exist_ok=True)

    text = generate_briefing_text()
    if not text:
        print("Claude returned no briefing text today -- skipping.")
        return
    text = _sanitize_for_speech(text)

    today = datetime.now(timezone.utc)
    filename = f"{today:%Y-%m-%d}.mp3"
    audio_path = EPISODES_DIR / filename

    # Saved alongside the audio so the generated script can be inspected directly,
    # instead of only being able to listen to the synthesized result.
    text_path = EPISODES_DIR / f"{today:%Y-%m-%d}.txt"
    text_path.write_text(text)

    synthesize_audio(text, audio_path)
    duration_seconds = get_duration_seconds(audio_path)

    episodes = load_episode_log()
    episodes = upsert_episode(episodes, {
        "title": f"Briefing -- {today:%B %-d, %Y}",
        "pub_date": today.strftime("%a, %d %b %Y %H:%M:%S +0000"),
        "filename": filename,
        "file_size": audio_path.stat().st_size,
        "duration_seconds": duration_seconds,
    })
    save_episode_log(episodes)

    FEED_PATH.write_text(build_feed_xml(episodes))
    print(f"Published episode: {filename}")


if __name__ == "__main__":
    main()
